version: '3'
services:
  mysql:
    container_name: mysql-task
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-task}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - symfony
volumes:
  my-db:
networks:
  symfony: